export const environment = {
    production: 'false',
    domain: 'https://localhost:7267',
    apiEndpoint: '/api',
    authentication: '/Autenticate',
    ordenesTrabajo: '/OrdenesTrabajo',
    mecanico: '/MecanicosController',
    validacion: '/Validacion',
    vehiculo: '/Vehiculo',
    licencia: '/LicenciasController',
    items: '/Items',
    tarea: '/Tarea',
    solicitudRepuesto: '/SolicitudRepuesto',
    adquisicion: '/compras',
    proveedor: '/ProveedorController',
    magnitud: '/MagnitudesController',
    adjuntos: '/Adjuntos',
    archivos: '/archivos',
    tipoVehiculo: '/TipoVehiculo',
    propietario: '/RegistroPropietario',
    detalleCompra: '/DetallesCompra',
    conversionUnidades: '/ConversionUnidades',
    cliente: '/Clientes',
    reporte: '/Reportes',
    usuarios: '/Usuarios',
    ordenMecanico: '/OrdenMecanico',
    impuesto: '/Impuesto',
    persona: '/Persona',
};

